config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :papers
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :pages
  root to: "pages#index"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/page.rb
class Page < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "500x500>", thumb: "400x350#" }, default_url: "/images/:style/missing.png" 
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  ratyrate_rateable "speed"
  has_attached_file :image, styles: { medium: "500x500>", thumb: "350x250#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  extend FriendlyId
  friendly_id :name
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.order('created_at DESC').page(params[:page]).per(6)
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :content, :avatar)
    end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:name, :content, :image)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def papers_contents
		@papers = Paper.all		
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/layouts/_footer.html.erb
<!--
==================================================
Call To Action Section Start
================================================== -->
<section id="call-to-action">
    <div class="container">
       <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h2 class="title wow fadeInDown" data-wow-delay=".3s" data-wow-duration="500ms">SO WHAT YOU THINK ?</h1>
                    <p class="wow fadeInDown" data-wow-delay=".5s" data-wow-duration="500ms">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium.</p>
                    <a href="contact.html" class="btn btn-default btn-contact wow fadeInDown" data-wow-delay=".7s" data-wow-duration="500ms">Contact With Me</a>
                </div>
            </div>
            
        </div>
    </div>
</section>

app/views/layouts/_paper.html.erb
              <section id="works" class="works">
                <div class="container1">
                    <div class="section-heading">
                        <h1 class="title wow fadeInDown" data-wow-delay=".3s">Latest Works</h1>
                    </div>
                                <div class="row">
                                    <div class="column-xs-1 epz">
                                    <% @papers = papers_contents %>
                                    <% @papers.limit(3).each do |paper| %>
                                    </div>
                                    <div class="alert1 alert-info1 column-sm-4 thumbnail2 row epz1">
                                    <center><h3><%= link_to paper.name, paper %></h3></center>
                                        <div class="image1">
                                        <h3><td><%= image_tag paper.image.url(:thumb) %></td></h3>
                                        </div>
                                    <% end %>
                                    </div>
                                </div>
                    </div>
              </section>   

app/views/layouts/_slider.html.erb
</body>
    <div id="slideshow" class="imageresize">

      <div>
        <img src="../images/Slider/1.jpg">
      </div>
      <div>
        <img src="../images/Slider/2.jpg">
      </div>
      <div>
        <img src="../images/Slider/3.jpg">
      </div>
      <div>
        <img src="../images/Slider/4.jpg">
      </div>
      <div>
        <img src="../images/Slider/5.jpg">
      </div>
          <center><section class="cd-intro block wow fadeInUp">
            <h1 class="wow fadeInUp animated cd-headline slide">
            <span>HI, MY NAME IS JONATHON & I AM A</span><br>
            <span class="cd-words-wrapper">
                <b class="is-visible">DESIGNER</b>
                <b>DEVELOPER</b>
                <b>FATHER</b>
            </span>
            </h1>
          </section> <!-- cd-intro -->
          <h2 class="wow fadeInUp animated">
          With 10 years experience, I've occupied many roles including digital design director,<br> web designer and developer. This site showcases some of my work.
          </h2>
          <% if user_signed_in? %>
          <%= link_to 'Шинэ зохиол нийтлэх', new_paper_path, :class => "btn-lines dark light wow fadeInUp animated btn btn-default btn-green" %>
          <% else %>
          <%= link_to 'Sign up', new_user_registration_path, :class => "btn-lines dark light wow fadeInUp animated btn btn-default btn-green" %>
          <% end %>
        </center>
    </div>
</body> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <title>PageSampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<html class="no-js">
    <head>
        <!-- Basic Page Needs
        ================================================== -->
        <meta charset="utf-8">  
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="icon" type="image/png" href="images/favicon.png">
        <title>SoyolErdem ITCLUB</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="">
        <!-- Mobile Specific Metas
        ================================================== -->
        <meta name="format-detection" content="telephone=no">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- Template CSS Files


        ==================================================
        Header Section Start
        ================================================== -->
        <header id="top-bar" class="navbar-fixed-top animated-header">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div class="navbar-brand">
                        <a href="index.html" >
                            <img src="images/logo.png" alt="">
                        </a>
                    </div>
                    <!-- /logo -->
                </div>
                <!-- main menu -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div class="main-menu">
                        <ul class="nav navbar-nav navbar-right">
                            <% if current_user %>
                                <li><%= link_to 'Pages', pages_path %></li>
                                <li><%= link_to 'Papers', papers_path %></li>
                            <% else %>
                                <li><%= link_to 'Pages', pages_path %></li>
                                <li><%= link_to 'Papers', papers_path %></li>
                                <li><%= link_to 'Login', user_session_path %></li>
                            <% end %>
                            <li class="dropdown">
                                <div class="btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                        <% if current_user %>
                                            <%= image_tag(current_user.avatar.url(:thumb), class: "round-image-50 ") %>
                                        <% end %>
                                    <span class="caret"></span></div>
                                    <div class="dropdown-menu">
                                    <ul>
                                        <li><% if current_user %></li>
                                        <li>Hi, <%= current_user.name %></li>
                                        <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                                            <li><% if current_user %></li>
                                            <li><%= link_to 'Admin Dashboard', rails_admin_path %></li>
                                            <% end -%>
                                        <li><%= link_to 'new content', new_page_path %></li>
                                        <li><%= link_to 'New Paper', new_paper_path %></li>
                                        <li><%= link_to('logout', destroy_user_session_path, :method => :delete) %></li>
                                    </ul>      
                                    </div>

                                </div>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            </div>
        </header>
            <%= yield %> 
            <!--
            ==================================================
            Footer Section Start
            ================================================== -->
            <footer id="footer">
                <div class="container">
                    <div class="col-md-8">
                        <p class="copyright">Copyright: <span>2016</span> . Developed by <a href="#">SoyolErdem IT Club</a></p>
                    </div>
                    <div class="col-md-4">
                        <!-- Social Media -->
                        <ul class="social">
                            <li>
                                <a href="http://wwww.fb.com/themefisher" class="Facebook">
                                    <i class="ion-social-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="http://wwww.twitter.com/themefisher" class="Twitter">
                                    <i class="ion-social-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="Linkedin">
                                    <i class="ion-social-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="http://wwww.fb.com/themefisher" class="Google Plus">
                                    <i class="ion-social-googleplus"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </footer> <!-- /#footer -->
                
        </body>
    </html>

app/views/pages/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//mochirotest1.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/pages/_form.html.erb
<%= form_for @page, html: { multipart: true } do |form| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :content %><br>
    <%= form.cktext_area :content %>
  </div>
  <div class="field">
    <%= form.label :avatar %><br>
    <%= form.file_field :avatar %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="alert1 alert-info1 releaseInfo">

<h1>Editing Page</h1>

<%= render 'form' %>
</div>
<center>
<div class="button2">
<p><%= link_to 'Show', @page, :class => "btn btn-default btn-green" %>
<%= link_to 'Back', pages_path, :class => "btn btn-default btn-green" %></p>
</div>
</center>

app/views/pages/index.html.erb
<%= render 'layouts/slider' %>
  <section id="works" class="works">
    <div class="container1">
      <div class="section-heading">
      <h1 class="title wow fadeInDown" data-wow-delay=".3s">Latest Works</h1>
      </div>
        <div class="row">
          <% @pages.each do |page| %>
          <div class="col-sm-4 column-xs-1 epz">
            <div class="thumbnails">
              <figure class="wow fadeInLeft animated portfolio-item" data-wow-duration="500ms" data-wow-delay="0ms">
                <div class="img-wrapper">
                  <%= image_tag page.avatar.url(:thumb) %>
                    <div class="overlay">
                      <div class="buttons">
                        <%= link_to 'Show', page %>
                          <!-- User login hiij orson tohioldold edit, destroy pathuud haragdana -->
                            <% if user_signed_in? %>
                              <%= link_to 'Edit', edit_page_path(page) %>
                              <%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                      </div>
                    </div>
            </div>
                </div>
                  <figcaption>
                    <h4>
                      <%= page.name %>
                    </h4>
                    <h3>
                        <%= page.content.html_safe %>
                    </h3>
                  </figcaption>
                </figure>
            </div>
            <% end %>
          </div>
        </div>
    </div>
    <center><%= paginate(@pages) %></center>
    </section>
<%= render 'layouts/paper' %>

<%= render 'layouts/footer' %>

app/views/pages/new.html.erb
<div class="alert1 alert-info1 releaseInfo">
<h1>New Page</h1>

<%= render 'form' %>
</div>
<center>
<div class="button2">
<p>
<%= link_to 'Back', pages_path, :class => "btn btn-default btn-green" %>
</p>
</div>
</center>

app/views/pages/show.html.erb
<center>
<div class="alert1 alert-info1 releaseInfo">
	<h4>
	  <%= @page.name %>
	</h4>
	
	<h4>
	  <%= @page.content.html_safe %>
	</h4>

		<div class="row">
		  <div class="epz">
            <div class="thumbnails">
                <div class="img-wrapper">
                	
					<%= image_tag @page.avatar.url(:medium) %>
					
</div>
					<div class="button1">
					<center><p><% if user_signed_in? %>
					<%= link_to 'Edit', edit_page_path(@page), :class => "btn btn-default btn-green" %>
					<% end %>
					<%= link_to 'Back', pages_path, :class => "btn btn-default btn-green"%>
					</p>

					<%= render 'disqus' =%>
					
					</center>
					</div>
				</div>
			</div>
		  </div>
		 </div>
</center>
<!-- Hereglegch hevterch orson tohioldold edit heseg haragdana -->
<!-- davhar zagvar -->

app/views/papers/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//mochirotest1.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/papers/_form.html.erb
<%= form_for @paper, html: { multipart: true } do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
    <%= tinymce %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<div class="alert1 alert-info1 releaseInfo">
<h1>Editing Paper</h1>

<%= render 'form' %>
</div>
<center>
<div class="button2">
<p>
<%= link_to 'Show', @paper, :class => "btn btn-default btn-green" %> 
<%= link_to 'Back', papers_path, :class => "btn btn-default btn-green" %>
</p>
</center>

app/views/papers/index.html.erb
  <section id="works" class="works">
    <div class="container1">
      <div class="section-heading">
      <h1 class="title wow fadeInDown" data-wow-delay=".3s">Papers</h1>
      </div>
        <div class="row">
          <% @papers.each do |paper| %>
          <div class="col-sm-4 column-xs-1 epz">
            <div class="thumbnails">
              <figure class="wow fadeInLeft animated portfolio-item" data-wow-duration="500ms" data-wow-delay="0ms">
                <div class="img-wrapper">
                    <td><%= paper.name %></td>
                    <td><%= paper.content %></td>
                    <td><%= image_tag paper.image.url(:thumb) %></td>
                    <div class="overlay">
                      <div class="buttons">
                        <%= link_to 'Show', paper %>
                          <!-- User login hiij orson tohioldold edit, destroy pathuud haragdana -->
                            <% if user_signed_in? %>
                              <%= link_to 'Edit', edit_paper_path(paper) %>
                              <%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                      </div>
                    </div>
            </div>
                </div>
                  <figcaption>
                    <h4>
                      <%= paper.name %>
                    </h4>
                    <h3>
                        <%= paper.content.html_safe %>
                    </h3>
                  </figcaption>
                </figure>
            </div>
            <% end %>
          </div>
        </div>
    </div>
    </section>

app/views/papers/new.html.erb
<div class="alert1 alert-info1 releaseInfo">
<h1>New Paper</h1>

<%= render 'form' %>
</div>
<center>
<div class="button2">
<p>
<%= link_to 'Back', papers_path, :class => "btn btn-default btn-green" %>
</p>
</div>
</center>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<div class="alert1 alert-info1 releaseInfo">

<h3>
  <%= @paper.name %>
</h3>

Vote | <%= @paper.rates("speed").count %> ratings :
   <%= rating_for @paper, "speed", :enable_half => true, :half_show => true, :disable_after_rate => false, :star => 10 %>
<br>

    <div class="row">
      <div class="epz">
            <div class="thumbnails">
                <div class="img-wrapper">
                <%= image_tag @paper.image.url(:medium) %>
                </div>
            </div>
      </div>
    </div>

  <h4>
  <%= @paper.content.html_safe %>
</h4>

</div>
</center>

<%= render 'disqus' =%>

<center>
	<div class="button2">
		<p>
        <%= link_to 'Edit', edit_paper_path(@paper), :class => "btn btn-default btn-green" %>
        <%= link_to 'Back', papers_path, :class => "btn btn-default btn-green" %>
        </p>
</center>